### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rahulvas** [w201rdada/portfolio-adaraliao#1]
I like the idea a lot actually. My only concern is getting the information. Will stores like Whole Foods, etc. willingly give up their price information? Additionally, the part about "availability at restaurants" seems like it would be difficult to do. Any ideas on how you would go about finding this data. 

I also thinking adding an inventory of a users pantry can help speed up the process and suggest using things that the owner already owns. 

I think once the data is gathered and complete, this would be a really good tool to use.

**Comment by adaraliao** [comment]
Hi Rahul,
Thanks for the advice and review! Good point about Whole Foods and Yelp giving access to their data...I had not thought too much on ability to scrap from their websites (not sure if there's some kind of data protection thing). I was thinking of scraping data from grocery stores' websites and yelp's website, will need to dig into this (unless I hit the limit of my skills). If there is no free access to websites' data, I will need to find a retailer's website that lets Python download their data.

The users' pantry is a great idea! I will have the pantry inventory as part of the suggestions for dishes. Not sure how to actually execute that algorithmn but the concept is good.

Thanks!
