### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by PeteTrenk** [w201rdada/portfolio-adaraliao#2]
I love the problem this tries to solve for. We struggle with it every night (literally just had a conversation about it an hour ago), so i think it resonates on a wide scale. My understanding is that you want to develop an application that streamlines and customizes the decision making process behind "what to eat" for health-conscious individuals. 

I really like the background context with respect to the challenges. Accessible, quality food is definitely a bigger problem than most people think. Even in LA there are quite a few "food deserts". I think there were even a couple MIDS capstones that focused on "food deserts". Another challenge might also be pricing of quality food. (I'm still waiting for the "amazon prices" to take shape at Whole Foods :).

Something that came to mind when reading your idea was Blue Apron. I know that there are a handful of companies that are focusing on this market. Maybe introducing where those companies fall short (too expensive??not as personalized??) could also be included in your background context.

What will be interesting is if you can scrape prices from the grocer's website. Looking forward to seeing how this develops

**Comment by adaraliao** [comment]
Hi Pete,
Thanks for the review and thoughtful comments! I like that you brought up accessibility and "food deserts" which I had not thought of. That is a social issue I can address; not every user has access to quality ingredients. I read somewhere that Whole Foods looks at the education and income levels of an area when deciding on locations. I'll check out the MIDS capstone projects! I will mention how my project (need a catchier name) should take into account ingredients within reasonable distance from user's location (10miles).

I had not thought of Blue Apron and HelloFresh, but now that you mentioned it, I cannot believe I missed this similarity! I will address this in my next commit, will need to think about what differentiates my project. Good point!

Thank you!
